---
book_repo: pivotal-cf/docs-book-scdf
layout_repo: pivotal-cf/docs-layout-repo

broken_link_exclusions: iefix|arrowhead

public_host: docs.pivotal.io

elastic_search: true

sections:
- repository:
    name: pivotal-cf/docs-spring-cloud-dataflow
    ref: "v1.7"
  directory: scdf/1-7
  subnav_template: scdf_1_7_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: '1.7'
    changelog_href: http://docs.pivotal.io/scdf/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Spring Cloud Data Flow
    search_placeholder: Search SCDF 1.7
    url_prefix: scdf/1-7
    local_product_version: '1.7'
    local_header_links: []
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/scdf/1-6
        display_name: v1.6
      - url_prefix: https://docs.pivotal.io/scdf/1-5
        display_name: v1.5
      - url_prefix: https://docs.pivotal.io/scdf/1-4
        display_name: v1.4
      - url_prefix: https://docs.pivotal.io/scdf/1-3
        display_name: v1.3
      - url_prefix: https://docs.pivotal.io/scdf/1-2
        display_name: v1.2
      - url_prefix: https://docs.pivotal.io/scdf/1-1
        display_name: v1.1
      - url_prefix: https://docs.pivotal.io/scdf/1-0
        display_name: v1.0
- repository:
    name: pivotal-cf/docs-spring-cloud-dataflow
    ref: "v1.6"
  directory: scdf/1-6
  subnav_template: scdf_1_6_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: '1.7'
    changelog_href: http://docs.pivotal.io/scdf/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Spring Cloud Data Flow
    search_placeholder: Search SCDF 1.6
    url_prefix: scdf/1-6
    local_product_version: '1.6'
    local_header_links: []
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/scdf/1-7
        display_name: v1.7
      - url_prefix: https://docs.pivotal.io/scdf/1-5
        display_name: v1.5
      - url_prefix: https://docs.pivotal.io/scdf/1-4
        display_name: v1.4
      - url_prefix: https://docs.pivotal.io/scdf/1-3
        display_name: v1.3
      - url_prefix: https://docs.pivotal.io/scdf/1-2
        display_name: v1.2
      - url_prefix: https://docs.pivotal.io/scdf/1-1
        display_name: v1.1
      - url_prefix: https://docs.pivotal.io/scdf/1-0
        display_name: v1.0
- repository:
    name: pivotal-cf/docs-spring-cloud-dataflow
    ref: "v1.5"
  directory: scdf/1-5
  subnav_template: scdf_1_5_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: '1.7'
    changelog_href: http://docs.pivotal.io/scdf/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Spring Cloud Data Flow
    search_placeholder: Search SCDF 1.5
    url_prefix: scdf/1-5
    local_product_version: '1.5'
    local_header_links: []
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/scdf/1-7
        display_name: v1.7
      - url_prefix: https://docs.pivotal.io/scdf/1-6
        display_name: v1.6
      - url_prefix: https://docs.pivotal.io/scdf/1-4
        display_name: v1.4
      - url_prefix: https://docs.pivotal.io/scdf/1-3
        display_name: v1.3
      - url_prefix: https://docs.pivotal.io/scdf/1-2
        display_name: v1.2
      - url_prefix: https://docs.pivotal.io/scdf/1-1
        display_name: v1.1
      - url_prefix: https://docs.pivotal.io/scdf/1-0
        display_name: v1.0
- repository:
    name: pivotal-cf/docs-spring-cloud-dataflow
    ref: "v1.4"
  directory: scdf/1-4
  subnav_template: scdf_1_4_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: '1.7'
    changelog_href: http://docs.pivotal.io/scdf/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Spring Cloud Data Flow
    search_placeholder: Search SCDF 1.4
    url_prefix: scdf/1-4
    local_product_version: '1.4'
    local_header_links: []
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/scdf/1-7
        display_name: v1.7
      - url_prefix: https://docs.pivotal.io/scdf/1-6
        display_name: v1.6
      - url_prefix: https://docs.pivotal.io/scdf/1-5
        display_name: v1.5
      - url_prefix: https://docs.pivotal.io/scdf/1-3
        display_name: v1.3
      - url_prefix: https://docs.pivotal.io/scdf/1-2
        display_name: v1.2
      - url_prefix: https://docs.pivotal.io/scdf/1-1
        display_name: v1.1
      - url_prefix: https://docs.pivotal.io/scdf/1-0
        display_name: v1.0
- repository:
    name: pivotal-cf/docs-spring-cloud-dataflow
    ref: "v1.3"
  directory: scdf/1-3
  subnav_template: scdf_1_3_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: '1.7'
    changelog_href: http://docs.pivotal.io/scdf/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Spring Cloud Data Flow
    search_placeholder: Search SCDF 1.3
    url_prefix: scdf/1-3
    local_product_version: '1.3'
    local_header_links: []
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/scdf/1-7
        display_name: v1.7
      - url_prefix: https://docs.pivotal.io/scdf/1-6
        display_name: v1.6
      - url_prefix: https://docs.pivotal.io/scdf/1-5
        display_name: v1.5
      - url_prefix: https://docs.pivotal.io/scdf/1-4
        display_name: v1.4
      - url_prefix: https://docs.pivotal.io/scdf/1-2
        display_name: v1.2
      - url_prefix: https://docs.pivotal.io/scdf/1-1
        display_name: v1.1
      - url_prefix: https://docs.pivotal.io/scdf/1-0
        display_name: v1.0
- repository:
    name: pivotal-cf/docs-spring-cloud-dataflow
    ref: "v1.2"
  directory: scdf/1-2
  subnav_template: scdf_1_2_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: '1.7'
    changelog_href: http://docs.pivotal.io/scdf/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Spring Cloud Data Flow
    search_placeholder: Search SCDF 1.2
    url_prefix: scdf/1-2
    local_product_version: '1.2'
    local_header_links: []
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/scdf/1-7
        display_name: v1.7
      - url_prefix: https://docs.pivotal.io/scdf/1-6
        display_name: v1.6
      - url_prefix: https://docs.pivotal.io/scdf/1-5
        display_name: v1.5
      - url_prefix: https://docs.pivotal.io/scdf/1-4
        display_name: v1.4
      - url_prefix: https://docs.pivotal.io/scdf/1-3
        display_name: v1.3
      - url_prefix: https://docs.pivotal.io/scdf/1-1
        display_name: v1.1
      - url_prefix: https://docs.pivotal.io/scdf/1-0
        display_name: v1.0
- repository:
    name: pivotal-cf/docs-spring-cloud-dataflow
    ref: "v1.1"
  directory: scdf/1-1
  subnav_template: scdf_1_1_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: '1.7'
    changelog_href: http://docs.pivotal.io/scdf/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Spring Cloud Data Flow
    search_placeholder: Search SCDF 1.1
    url_prefix: scdf/1-1
    local_product_version: '1.1'
    local_header_links: []
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/scdf/1-7
        display_name: v1.7
      - url_prefix: https://docs.pivotal.io/scdf/1-6
        display_name: v1.6
      - url_prefix: https://docs.pivotal.io/scdf/1-5
        display_name: v1.5
      - url_prefix: https://docs.pivotal.io/scdf/1-4
        display_name: v1.4
      - url_prefix: https://docs.pivotal.io/scdf/1-3
        display_name: v1.3
      - url_prefix: https://docs.pivotal.io/scdf/1-2
        display_name: v1.2
      - url_prefix: https://docs.pivotal.io/scdf/1-0
        display_name: v1.0
- repository:
    name: pivotal-cf/docs-spring-cloud-dataflow
    ref: "v1.0"
  directory: scdf/1-0
  subnav_template: scdf_1_0_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: '1.7'
    changelog_href: http://docs.pivotal.io/scdf/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Spring Cloud Data Flow
    search_placeholder: Search SCDF 1.0
    url_prefix: scdf/1-0
    local_product_version: '1.0'
    local_header_links: []
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/scdf/1-7
        display_name: v1.7
      - url_prefix: https://docs.pivotal.io/scdf/1-6
        display_name: v1.6
      - url_prefix: https://docs.pivotal.io/scdf/1-5
        display_name: v1.5
      - url_prefix: https://docs.pivotal.io/scdf/1-4
        display_name: v1.4
      - url_prefix: https://docs.pivotal.io/scdf/1-3
        display_name: v1.3
      - url_prefix: https://docs.pivotal.io/scdf/1-2
        display_name: v1.2
      - url_prefix: https://docs.pivotal.io/scdf/1-1
        display_name: v1.1
